PG_PORT : 5432
PG_DATABASE : aaq-template-db-test
PG_USERNAME: flask_test
MODEL_PORT : 9904
MODEL_PROTOCOL : http
TRUE_URGENCY: "COLUMN IN THE DATA REFERRING TO ACTUAL URGENCY. SHOULD HAVE VALUES ONLY AS YES AND NO"
QUERY_COL: "COLUMN IN DATA REFERRING TO INBOUND MESSAGES"
THRESHOLD_CRITERIA: "SET A VALUE FOR RECALL BELOW WHICH AN EMAIL WILL BE SENT THROUGH AWS SNS TO SUBSCRIBERS"
