{
 "title": "MomConnect Urgency Detection",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_status{c1_name=\"MC Core App Healthcheck\"}"
    }
   ]
  },
  {
   "title": "inbound message : SUCCESS : Last 1hr",
   "type": "stat",
   "description": "HTTP Response Status Code was 200",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ud_inbound_by_status_total{status=\"200\"}[1h]))"
    }
   ]
  },
  {
   "title": "inbound message : FAILURE : Last 12hrs",
   "type": "stat",
   "description": "HTTP Response Status Code was NOT 200",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ud_inbound_by_status_total{status!=\"200\"}[24h]))"
    }
   ]
  },
  {
   "title": "feedback message : SUCCESS : Last 1hr",
   "type": "stat",
   "description": "HTTP Response Status Code was 200",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ud_feedback_by_status_total{status=\"200\"}[1h]))"
    }
   ]
  },
  {
   "title": "feedback message : FAILURE : Last 12hrs",
   "type": "stat",
   "description": "HTTP Response Status Code was NOT 200",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ud_feedback_by_status_total{status!=\"200\"}[24h]))"
    }
   ]
  },
  {
   "title": "Number of calls to `/inbound/check`",
   "type": "timeseries",
   "description": "The main endpoint in the urgency detection app",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(ud_inbound_by_status_current_count[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of calls to `/inbound/feedback/`",
   "type": "timeseries",
   "description": "The feedback endpoint in the urgency detection app",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(ud_feedback_by_status_current_count{status=\"200\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg response time for `/inbound/check`",
   "type": "timeseries",
   "description": "Response time for urgency detection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ud_inbound_by_status_current_sum{}/ud_inbound_by_status_current_count{}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg response time for `/inbound/feedback`",
   "type": "timeseries",
   "description": "Response time for urgency detection feedback",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "ud_feedback_by_status_current_sum/ud_feedback_by_status_current_count",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}